name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or commit to publish. The ref must be a chore(release) commit
        default: main

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write
      actions: read
      deployments: write
      packages: write
    steps:
      - name: Publish
        env:
          ACTIONS_RUNNER_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: dynamic-labs-oss/public-wallet-connectors/.github/actions/release@main
        with:
          type: publish
          ref: ${{ github.event.inputs.ref }}
